#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source .fonctions
source /usr/share/yunohost/helpers

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
admin=$YNH_APP_ARG_ADMIN
language=$YNH_APP_ARG_LANGUAGE

app=$YNH_APP_INSTANCE_NAME

path_url=/ftp_webapp_$admin
parent_dir=/var/www/webapp_$admin
final_path=$parent_dir/netftp

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
#=================================================

CHECK_USER "$admin"	# Vérifie la validité de l'user admin
path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.
CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.
test ! -e "$final_path" || ynh_die "This path already contains a folder"	# Vérifie que le dossier de destination n'est pas déjà utilisé.

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path_url
ynh_app_setting_set $app admin $admin

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================

port=$(ynh_find_port 21)	# Cherche un port libre.
# Ouvre le port dans le firewall
ALL_QUIET sudo yunohost firewall allow TCP $port
ynh_app_setting_set $app port $port

#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_install_app_dependencies pure-ftpd-ldap

#=================================================
# SPECIFIC SETUP
#=================================================
# CREATE PARENT DIR IF NOT EXIST
#=================================================

# Créer le dossier parent des webapp pour l'utilisateur
if test ! -d $parent_dir
then	# Créer le dossier parent uniquement si il n'existe pas
	sudo mkdir $parent_dir
	# Set permissions
	sudo chmod 755 -R $parent_dir
	sudo chown -R root: $parent_dir
else
	echo "Création du dossier $parent_dir ignorée, le dossier existe déjà."
fi

#=================================================
# SETUP PURE-FTPD
#=================================================

# Change user ID in configurations
sed -i "s@__FTPUSER__@$admin@g" ../conf/ldap.conf
sed -i "s@__FTPDIR__@$parent_dir@g" ../conf/ldap.conf

# Adapt PureFTPd configuration
sudo cp ../conf/ldap.conf /etc/pure-ftpd/db/
sudo sh -c 'echo "yes" > /etc/pure-ftpd/conf/NoAnonymous'
sudo sh -c 'echo "yes" > /etc/pure-ftpd/conf/ChrootEveryone'
sudo sh -c 'echo "no" > /etc/pure-ftpd/conf/UnixAuthentication'
sudo sh -c 'echo "50000 50100" > /etc/pure-ftpd/conf/PassivePortRange'
sudo sh -c "echo "$port" > /etc/pure-ftpd/conf/Bind"

#=================================================
# RESTART PURE-FTPD
#=================================================

sudo systemctl restart pure-ftpd-ldap

#=================================================
# DOWNLOAD, CHECK AND UNPACK NET2FTP
#=================================================

ynh_app_setting_set $app final_path $final_path
SETUP_SOURCE_ZIP	# Télécharge la source, décompresse et copie dans $final_path
sudo cp -a $final_path/files_to_upload/. $final_path
sudo rm -r $final_path/files_to_upload

#=================================================
# NGINX CONFIGURATION
#=================================================

# Copie le fichier de config nginx
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/netftp_$admin.conf
# Modifie les variables dans le fichier de configuration nginx
sudo sed -i "s@__PATHTOCHANGE__@$path_url@g" /etc/nginx/conf.d/$domain.d/netftp_$admin.conf
sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/netftp_$admin.conf
sudo sed -i "s@__NAMETOCHANGE__@$app@g" /etc/nginx/conf.d/$domain.d/netftp_$admin.conf



#=================================================
# CREATE DEDICATED USER
#=================================================

ynh_system_user_create $app	# Créer un utilisateur système dédié à l'app

#=================================================
# PHP-FPM CONFIGURATION
#=================================================

POOL_FPM	# Créer le fichier de configuration du pool php-fpm et le configure.

#=================================================
# GENERIC FINALISATION
#=================================================
# SECURING FILES AND DIRECTORIES
#=================================================

# Les fichiers appartiennent à root
sudo chown -R root: $final_path
# www-data doit avoir les droits d'écriture sur le dossier temp.
sudo mkdir -p $final_path/temp
sudo chown -R $app: $final_path/temp

#=================================================
# SETUP LOGROTATE
#=================================================

ynh_use_logrotate

#=================================================
# ENABLE SERVICE IN ADMIN PANELS
#=================================================

sudo yunohost service add pure-ftpd-ldap --log "/var/log/pure-ftpd/transfer.log"

#=================================================
# RELOAD NGINX
#=================================================

sudo systemctl reload nginx
