#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source .fonctions
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

admin=$(ynh_app_setting_get $app admin)
domain=$(ynh_app_setting_get $app domain)
port=$(ynh_app_setting_get $app port)
parent_dir=/var/www/webapp_$admin

#=================================================
# STANDARD REMOVE
#=================================================
# DISABLE SERVICE IN ADMIN PANEL
#=================================================

if sudo yunohost service status | grep -q $app	# Test l'existence du service dans Yunohost
then
	echo "Remove $app service"
	sudo yunohost service remove $app
fi

#=================================================
# REMOVE DEPENDENCIES
#=================================================

ynh_remove_app_dependencies

#=================================================
# REMOVE THE MAIN DIR OF THE APP
#=================================================

SECURE_REMOVE '$parent_dir/netftp'	# Suppression du dossier de l'application

#=================================================
# REMOVE THE NGINX CONFIGURATION
#=================================================

REMOVE_NGINX_CONF	# Suppression de la configuration nginx

#=================================================
# REMOVE THE PHP-FPM CONFIGURATION
#=================================================

REMOVE_FPM_CONF	# Suppression de la configuration du pool php-fpm

#=================================================
# REMOVE THE LOGROTATE CONFIG
#=================================================

ynh_remove_logrotate	# Suppression de la configuration de logrotate

#=================================================
# CLOSE A PORT
#=================================================

if sudo yunohost firewall list | grep -q "\- $port$"
then
	echo "Close port $port"
	QUIET sudo yunohost firewall disallow TCP $port
fi

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE PARENT DIR IF IT'S EMPTY
#=================================================

# Vérifie si le dossier parent est vide. Ce qui signifie que toutes les webapp ont été désinstallées. Ainsi que le client ftp net2ftp.
if [ -e "$parent_dir" ]
then
	if test -z "$(ls $parent_dir | head -n1)"
	then
		sudo rmdir "$parent_dir"
	fi
fi

#=================================================
# GENERIC FINALISATION
#=================================================
# REMOVE DEDICATED USER
#=================================================

ynh_system_user_delete $app
