#!/bin/bash

app=ftp_webapp

# Récupère les infos de l'application.
admin=$(sudo yunohost app setting $app admin)
domain=$(sudo yunohost app setting $app domain)
port=$(sudo yunohost app setting $app port)
parent_dir=/var/www/webapp_$user

# Suppression du dossier de l'application
sudo rm -rf $parent_dir/netftp

# Suppression de la configuration nginx
sudo rm -f /etc/nginx/conf.d/$domain.d/netftp_$admin.conf

# Suppression de la configuration du pool php-fpm
sudo rm -f /etc/php5/fpm/pool.d/$app.conf
sudo rm -f /etc/php5/fpm/conf.d/20-$app.ini

# Vérifie si le dossier parent est vide. Ce qui signifie que toutes les webapp ont été désinstallées. Ainsi que le client ftp net2ftp.
if test -z "$(ls $parent_dir | head -n1)"
then
    sudo rmdir $parent_dir
fi

# Vérifie si il reste encore au moins une instance de net2ftp dans un dossier de webapp
if test -z "$(ls /etc/nginx/conf.d/$domain.d/ | grep netftp_ | head -n1)"
then	# Si il n'y a plus aucun net2ftp installé, désinstalle pure-ftpd
    sudo service pure-ftpd-ldap stop
    sudo apt-get purge -y -qq pure-ftpd-ldap pure-ftpd-common
    sudo yunohost service remove pure-ftpd-ldap
    sudo yunohost firewall disallow TCP $port
fi

# Suppression de la configuration de logrotate
sudo rm /etc/logrotate.d/$app

# Recharge la configuration Nginx et php5-fpm
sudo service nginx reload
sudo service php5-fpm reload
# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf
