#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source .fonctions
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

admin=$(ynh_app_setting_get $app admin)
domain=$(ynh_app_setting_get $app domain)
port=$(ynh_app_setting_get $app port)
language_file=$(ynh_app_setting_get $app language_file)

path_url=/ftp_webapp_$admin
parent_dir=/var/www/webapp_$admin
final_path=$parent_dir/netftp

#=================================================
# CHECK THE PATH
#=================================================

path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.

#=================================================
# SPECIFIC UPGRADE
#=================================================
# SETUP PURE-FTPD
#=================================================

# Change user ID in configurations
sed -i "s@__FTPUSER__@$admin@g" ../conf/ldap.conf
sed -i "s@__FTPDIR__@$parent_dir@g" ../conf/ldap.conf

# Adapt PureFTPd configuration
sudo cp ../conf/ldap.conf /etc/pure-ftpd/db/
sudo sh -c 'echo "yes" > /etc/pure-ftpd/conf/NoAnonymous'
sudo sh -c 'echo "yes" > /etc/pure-ftpd/conf/ChrootEveryone'
sudo sh -c 'echo "no" > /etc/pure-ftpd/conf/UnixAuthentication'
sudo sh -c 'echo "50000 50100" > /etc/pure-ftpd/conf/PassivePortRange'
sudo sh -c "echo "$port" > /etc/pure-ftpd/conf/Bind"

#=================================================
# RESTART PURE-FTPD
#=================================================

sudo systemctl restart pure-ftpd-ldap

#=================================================
# NGINX CONFIGURATION
#=================================================

# Et copie le fichier de config nginx
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/netftp_$admin.conf
# Modifie les variables dans le fichier de configuration nginx
sudo sed -i "s@__PATHTOCHANGE__@$path@g" /etc/nginx/conf.d/$domain.d/netftp_$admin.conf
sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/netftp_$admin.conf
sudo sed -i "s@__NAMETOCHANGE__@$app@g" /etc/nginx/conf.d/$domain.d/netftp_$admin.conf

#=================================================
# SETUP NET2FTP
#=================================================

# Configurer net2ftp
sed -i "s@__DOMAIN__@$domain@" ../conf/settings_authorizations.inc.php
sed -i "s@__LANG__@$language_file@" ../conf/settings.inc.php

# Copier les fichiers de config
CHECK_MD5_CONFIG "settings_authorizations.inc.php" "$final_path/settings_authorizations.inc.php"	# Créé un backup du fichier de config si il a été modifié.
sudo cp ../conf/settings_authorizations.inc.php $final_path
STORE_MD5_CONFIG "settings_authorizations.inc.php" "$final_path/settings_authorizations.inc.php"	# Réenregistre la somme de contrôle du fichier de config
CHECK_MD5_CONFIG "settings.inc.php" "$final_path/settings.inc.php"	# Créé un backup du fichier de config si il a été modifié.
sudo cp ../conf/settings.inc.php $final_path
STORE_MD5_CONFIG "settings.inc.php" "$final_path/settings.inc.php"	# Réenregistre la somme de contrôle du fichier de config

#=================================================
# CREATE DEDICATED USER
#=================================================

ynh_system_user_create $app	# Créer un utilisateur système dédié à l'app

#=================================================
# PHP-FPM CONFIGURATION
#=================================================

POOL_FPM	# Créer le fichier de configuration du pool php-fpm et le configure.

#=================================================
# GENERIC FINALISATION
#=================================================
# SECURING FILES AND DIRECTORIES
#=================================================

# Les fichiers appartiennent à root
sudo chown -R root: $final_path
# www-data doit avoir les droits d'écriture sur le dossier temp.
sudo chown -R $app: $final_path/temp

#=================================================
# SETUP LOGROTATE
#=================================================

ynh_use_logrotate

#=================================================
# RELOAD NGINX
#=================================================

sudo systemctl reload nginx
