#!/bin/bash

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

# Récupère les infos de l'application.
YNH_VERSION	# Récupère le numéro de version de Yunohost.
if [ $ynh_version = "2.4" ]; then
	app=$YNH_APP_INSTANCE_NAME
else
	app=ftp_webapp
fi
admin=$(sudo yunohost app setting $app admin)
domain=$(sudo yunohost app setting $app domain)
port=$(sudo yunohost app setting $app port)
language_file=$(sudo yunohost app setting $app language_file)
parent_dir=/var/www/webapp_$user

CHECK_PATH	# Vérifie et corrige la syntaxe du path.
path=/ftp_webapp_$admin
parent_dir=/var/www/webapp_$admin
final_path=$parent_dir/netftp

# Change user ID in configurations
sed -i "s@__FTPUSER__@$admin@g" ../conf/ldap.conf
sed -i "s@__FTPDIR__@$parent_dir@g" ../conf/ldap.conf

# Adapt PureFTPd configuration
sudo cp ../conf/ldap.conf /etc/pure-ftpd/db/
sudo sh -c 'echo "yes" > /etc/pure-ftpd/conf/NoAnonymous'
sudo sh -c 'echo "yes" > /etc/pure-ftpd/conf/ChrootEveryone'
sudo sh -c 'echo "no" > /etc/pure-ftpd/conf/UnixAuthentication'
sudo sh -c 'echo "50000 50100" > /etc/pure-ftpd/conf/PassivePortRange'
sudo sh -c "echo "$port" > /etc/pure-ftpd/conf/Bind"

# Restart PureFTPd
sudo service pure-ftpd-ldap restart

# Copie les fichiers additionnels ou modifiés.
sudo cp -a ../sources/ajouts/. "$final_path"
# Et copie le fichier de config nginx
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/netftp_$admin.conf

# Configurer net2ftp
sed -i "s@__DOMAIN__@$domain@" ../conf/settings_authorizations.inc.php
sed -i "s@__LANG__@$language_file@" ../conf/settings.inc.php

# Copier les fichiers de config
CHECK_MD5_CONFIG "settings_authorizations.inc.php" "$final_path/settings_authorizations.inc.php"	# Créé un backup du fichier de config si il a été modifié.
sudo cp ../conf/settings_authorizations.inc.php $final_path
STORE_MD5_CONFIG "settings_authorizations.inc.php" "$final_path/settings_authorizations.inc.php"	# Réenregistre la somme de contrôle du fichier de config
CHECK_MD5_CONFIG "settings.inc.php" "$final_path/settings.inc.php"	# Créé un backup du fichier de config si il a été modifié.
sudo cp ../conf/settings.inc.php $final_path
STORE_MD5_CONFIG "settings.inc.php" "$final_path/settings.inc.php"	# Réenregistre la somme de contrôle du fichier de config


# Configure les droits d'accès au fichiers
# -rw-r--r-- sur les fichiers
sudo find $final_path -type f -print0 | xargs -0 sudo chmod 644
# drwxr-xr-x sur les dossiers
# sudo find $final_path -type d | xargs sudo chmod 755
sudo find $final_path -type d -print0 | xargs -0 sudo chmod 755
# Les fichiers appartiennent à root
sudo chown -R root: $final_path

# www-data doit avoir les droits d'écriture sur le dossier temp.
sudo chown -R www-data: $final_path/temp

# Modifie les variables dans le fichier de configuration nginx
sudo sed -i "s@__PATHTOCHANGE__@$path@g" /etc/nginx/conf.d/$domain.d/netftp_$admin.conf
sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/netftp_$admin.conf
sudo sed -i "s@__NAMETOCHANGE__@$app@g" /etc/nginx/conf.d/$domain.d/netftp_$admin.conf


POOL_FPM	# Créer le fichier de configuration du pool php-fpm et le configure.

# Configuration de logrotate
sudo cp ../conf/logrotate /etc/logrotate.d/$app


# Recharge la configuration Nginx et php5-fpm
sudo service nginx reload
# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf
