#!/bin/bash

# Retrieve arguments
domain=$(sudo yunohost app setting ftp_webapp domain)
user=$(sudo yunohost app setting ftp_webapp ftp_user)

path=/ftp_webapp_$user
parent_dir=/var/www/webapp_$user
final_path=$parent_dir/netftp

# Change user ID in configurations
sed -i "s@FTPUSER@$user@g" ../conf/ldap.conf
sed -i "s@FTPDIR@$parent_dir@g" ../conf/ldap.conf

# Adapt PureFTPd configuration
sudo cp ../conf/ldap.conf /etc/pure-ftpd/db/
sudo sh -c 'echo "yes" > /etc/pure-ftpd/conf/NoAnonymous'
sudo sh -c 'echo "yes" > /etc/pure-ftpd/conf/ChrootEveryone'
sudo sh -c 'echo "no" > /etc/pure-ftpd/conf/UnixAuthentication'
sudo sh -c 'echo "50000 50100" > /etc/pure-ftpd/conf/PassivePortRange'
sudo sh -c 'echo "21021" > /etc/pure-ftpd/conf/Bind'

# Restart PureFTPd
sudo service pure-ftpd-ldap restart

# Copie du client ftp net2ftp
sudo cp -r ../sources/net2ftp $parent_dir/netftp

# Copie des fichiers modifiés de net2ftp
sudo cp -r ../sources/net2ftp_modif/* $parent_dir/netftp/

# Configurer net2ftp
sed -i "s@__DOMAIN__@$domain@" ../conf/settings_authorizations.inc.php

# Copier les fichiers de config
sudo cp ../conf/settings_authorizations.inc.php $parent_dir/netftp/
sudo cp ../conf/settings.inc.php $parent_dir/netftp/

# Appliquer permissions à net2ftp
sudo chmod 775 -R $parent_dir/netftp
sudo chown -hR www-data:www-data $parent_dir/netftp

# Modify Nginx configuration file and copy it to Nginx conf directory for net2ftp
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$parent_dir/netftp/@g" ../conf/nginx.conf
sed -i "s@NAMETOCHANGE@netftp@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/netftp_$user.conf

# Modify php-fpm pool configuration and copy it to php-fpm pool directory for net2ftp
sed -i "s@NAMETOCHANGE@netftp@g" ../conf/php-fpm.conf
sed -i "s@FINAL_PATH@$final_path@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/netftp.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
finalphpini=/etc/php5/fpm/conf.d/20-netftp.ini
sudo cp ../conf/php-fpm.ini $finalphpini
sudo chown root: $finalphpini

# Reload Nginx and php, and regenerate SSOwat conf
sudo service nginx reload
sudo service php5-fpm reload
sudo yunohost app ssowatconf
